---
docker_old_packages:
  - docker
  - docker-engine
  - docker.io
  - containerd
  - runc

docker_required_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  - python3
  - python3-pip
  - htop
  - ncdu
  - net-tools
  - open-vm-tools
  - tmux
  - tree
  - vim

docker_new_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io

docker_users:
  - ubuntu

pip_packages:
  - docker