---
- name: check docker-compose installation
  shell: "which docker-compose"
  ignore_errors: yes
  register: result

- name: skip docker-compose installation role
  meta: end_play
  when: result.rc == 0

- name: update apt cache and upgrade system
  apt:
    update_cache: yes
    upgrade: yes

- name: install required packages
  apt:
    name: "{{ docker_required_packages }}"
    state: present

- name: install docker python package
  pip:
    name: "{{ pip_packages }}"
    state: present